const CREATE_USER = "CREATE_USER";
const SELECTED_USER = "SELECTED_USER";
const FETCH_USERS_LIST = "FETCH_USERS_LIST";
const LOGOUT_USER = "LOGOUT_USER"

export {
    CREATE_USER,
    FETCH_USERS_LIST,
    SELECTED_USER,
    LOGOUT_USER
}